(ns day-002)

;;;; Project Euler #2 - Even Fibonacci Numbers

;;; Each new term in the Fibonacci sequence is generated by adding the previous two terms.
;;; By starting with 1 and 2, the first 10 terms will be:
;;;
;;; 1,2,3,5,8,13,21,34,55,89,...
;;;
;;; By considering the terms in the Fibonacci sequence whose values do not exceed
;;; four million, find the sum of the even-valued terms.

(def fib-seq ; Lazy seq from https://yankev.github.io/2017/05/15/fib_clj.html
  (letfn [(fib-add [[a b]]
            [b (+ a b)])]
    (map last (iterate fib-add [0 1]))))

(println "Answer:"
         (reduce + 0
                 (filter even?
                         (take-while #(< % 4000000) fib-seq))))
